"""ROS1 std_msgs message definitions for noetic.

Auto-generated by scripts/generate_ros1_messages.py
Source: https://github.com/ros/std_msgs/tree/noetic-devel/msg
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

import pybag.types as t


@dataclass(kw_only=True)
class Bool:
    __msg_name__ = 'std_msgs/Bool'

    data: t.bool


@dataclass(kw_only=True)
class Byte:
    __msg_name__ = 'std_msgs/Byte'

    data: t.byte


@dataclass(kw_only=True)
class Char:
    __msg_name__ = 'std_msgs/Char'

    data: t.ros1.char


@dataclass(kw_only=True)
class ColorRGBA:
    __msg_name__ = 'std_msgs/ColorRGBA'

    r: t.float32
    g: t.float32
    b: t.float32
    a: t.float32


@dataclass(kw_only=True)
class Duration:
    __msg_name__ = 'std_msgs/Duration'

    data: t.ros1.duration


@dataclass(kw_only=True)
class Empty:
    __msg_name__ = 'std_msgs/Empty'

    pass


@dataclass(kw_only=True)
class Float32:
    __msg_name__ = 'std_msgs/Float32'

    data: t.float32


@dataclass(kw_only=True)
class Float64:
    __msg_name__ = 'std_msgs/Float64'

    data: t.float64


@dataclass(kw_only=True)
class Header:
    __msg_name__ = 'std_msgs/Header'

    seq: t.uint32
    stamp: t.ros1.time
    frame_id: t.string


@dataclass(kw_only=True)
class Int16:
    __msg_name__ = 'std_msgs/Int16'

    data: t.int16


@dataclass(kw_only=True)
class Int32:
    __msg_name__ = 'std_msgs/Int32'

    data: t.int32


@dataclass(kw_only=True)
class Int64:
    __msg_name__ = 'std_msgs/Int64'

    data: t.int64


@dataclass(kw_only=True)
class Int8:
    __msg_name__ = 'std_msgs/Int8'

    data: t.int8


@dataclass(kw_only=True)
class MultiArrayDimension:
    __msg_name__ = 'std_msgs/MultiArrayDimension'

    label: t.string
    size: t.uint32
    stride: t.uint32


@dataclass(kw_only=True)
class String:
    __msg_name__ = 'std_msgs/String'

    data: t.string


@dataclass(kw_only=True)
class Time:
    __msg_name__ = 'std_msgs/Time'

    data: t.ros1.time


@dataclass(kw_only=True)
class UInt16:
    __msg_name__ = 'std_msgs/UInt16'

    data: t.uint16


@dataclass(kw_only=True)
class UInt32:
    __msg_name__ = 'std_msgs/UInt32'

    data: t.uint32


@dataclass(kw_only=True)
class UInt64:
    __msg_name__ = 'std_msgs/UInt64'

    data: t.uint64


@dataclass(kw_only=True)
class UInt8:
    __msg_name__ = 'std_msgs/UInt8'

    data: t.uint8


@dataclass(kw_only=True)
class MultiArrayLayout:
    __msg_name__ = 'std_msgs/MultiArrayLayout'

    dim: t.Array[MultiArrayDimension]
    data_offset: t.uint32


@dataclass(kw_only=True)
class ByteMultiArray:
    __msg_name__ = 'std_msgs/ByteMultiArray'

    layout: MultiArrayLayout
    data: t.Array[t.byte]


@dataclass(kw_only=True)
class Float32MultiArray:
    __msg_name__ = 'std_msgs/Float32MultiArray'

    layout: MultiArrayLayout
    data: t.Array[t.float32]


@dataclass(kw_only=True)
class Float64MultiArray:
    __msg_name__ = 'std_msgs/Float64MultiArray'

    layout: MultiArrayLayout
    data: t.Array[t.float64]


@dataclass(kw_only=True)
class Int16MultiArray:
    __msg_name__ = 'std_msgs/Int16MultiArray'

    layout: MultiArrayLayout
    data: t.Array[t.int16]


@dataclass(kw_only=True)
class Int32MultiArray:
    __msg_name__ = 'std_msgs/Int32MultiArray'

    layout: MultiArrayLayout
    data: t.Array[t.int32]


@dataclass(kw_only=True)
class Int64MultiArray:
    __msg_name__ = 'std_msgs/Int64MultiArray'

    layout: MultiArrayLayout
    data: t.Array[t.int64]


@dataclass(kw_only=True)
class Int8MultiArray:
    __msg_name__ = 'std_msgs/Int8MultiArray'

    layout: MultiArrayLayout
    data: t.Array[t.int8]


@dataclass(kw_only=True)
class UInt16MultiArray:
    __msg_name__ = 'std_msgs/UInt16MultiArray'

    layout: MultiArrayLayout
    data: t.Array[t.uint16]


@dataclass(kw_only=True)
class UInt32MultiArray:
    __msg_name__ = 'std_msgs/UInt32MultiArray'

    layout: MultiArrayLayout
    data: t.Array[t.uint32]


@dataclass(kw_only=True)
class UInt64MultiArray:
    __msg_name__ = 'std_msgs/UInt64MultiArray'

    layout: MultiArrayLayout
    data: t.Array[t.uint64]


@dataclass(kw_only=True)
class UInt8MultiArray:
    __msg_name__ = 'std_msgs/UInt8MultiArray'

    layout: MultiArrayLayout
    data: t.Array[t.uint8]
