name: Release Tag

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Semantic version bump to apply before tagging'
        required: true
        type: choice
        default: patch
        options:
          - patch
          - minor
          - major
      release_notes:
        description: 'Release notes for the GitHub release'
        required: false
        default: ''

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: latest

      - name: Prepare version
        id: version
        shell: bash
        run: |
          set -euo pipefail
          uv version --bump ${{ inputs.release_type }}
          CLEAN_VERSION="$(uv version --short)"
          if [ -z "$CLEAN_VERSION" ]; then
            echo "Version cannot be empty after bump" >&2
            exit 1
          fi
          echo "version=$CLEAN_VERSION" >> "$GITHUB_OUTPUT"
          echo "tag=v$CLEAN_VERSION" >> "$GITHUB_OUTPUT"

      - name: Commit and push version bump
        shell: bash
        env:
          VERSION: ${{ steps.version.outputs.version }}
          TAG: ${{ steps.version.outputs.tag }}
        run: |
          set -euo pipefail
          if git diff --quiet; then
            echo "No changes detected after version update."
            exit 1
          fi
          git config user.name "siliconlad"
          git config user.email "siliconlad@protonmail.com"
          git commit -am "chore: release $VERSION"
          git tag -a "$TAG" -m "Release $TAG"
          git push origin HEAD
          git push origin "$TAG"

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: ${{ steps.version.outputs.tag }}
          body: ${{ inputs.release_notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
