name: Release Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. 0.3.0 or v0.3.0)'
        required: true
      release_notes:
        description: 'Release notes for the GitHub release'
        required: false
        default: ''

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare version
        id: version
        shell: bash
        run: |
          RAW_VERSION="${{ inputs.version }}"
          CLEAN_VERSION="${RAW_VERSION#v}"
          if [ -z "$CLEAN_VERSION" ]; then
            echo "Version cannot be empty after removing optional 'v' prefix" >&2
            exit 1
          fi
          echo "version=$CLEAN_VERSION" >> "$GITHUB_OUTPUT"
          echo "tag=v$CLEAN_VERSION" >> "$GITHUB_OUTPUT"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: latest

      - name: Update project version files
        run: uv run python scripts/update_version.py "${{ steps.version.outputs.version }}"

      - name: Commit and push version bump
        shell: bash
        env:
          VERSION: ${{ steps.version.outputs.version }}
          TAG: ${{ steps.version.outputs.tag }}
        run: |
          set -euo pipefail
          if git diff --quiet; then
            echo "No changes detected after version update."
            exit 1
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "chore: release $VERSION"
          git tag -a "$TAG" -m "Release $TAG"
          git push origin HEAD
          git push origin "$TAG"

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: ${{ steps.version.outputs.tag }}
          body: ${{ inputs.release_notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
